community/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns=[
    path('user/',views.index),
    path('user/register/',views.register),
    path('user/login/',views.user_login),
    path('user/logout/',views.user_logout),
    path('user/resetpassword/',views.resetpassword),
    #纯后端接口
    path('user/getUserInfo/',views.getUserInfo),
        

]

community/community/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('posting.urls')),
    path('admin/', admin.site.urls),
]

community/posting/urls.py
from django.urls import path
from . import views

app_name='posting'
urlpatterns=[
    path('posting/',views.index,name='index'),
    path('posting/createposting/',views.createPosting), #发帖
    path('posting/createcomment/<int:postId>',views.createComment), #发评论
    path('posting/<str:postTitle>/',views.getPostByTitle), #查看帖子

]

community/accounts/models.py
from django.db import models
from django.utils.timezone import now #当前时间
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User

GENDER = {
            ('m','man'),
            ('w','woman'),
            ('s','secret')
        }

class BlogUser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,default=None, null=True)
    nickname = models.CharField('昵称', max_length=100, blank=True)
    mugshot = models.ImageField('头像', upload_to='upload/mugshots', blank=True)
    lastLoginDate = models.DateTimeField('最后一次登陆', default=now)
    icon = models.IntegerField('硬币数量',default=0)
    # lastLoginIP = models.GenericIPAddressField('最后一次登陆地址')
    telephone = models.CharField('电话号码',max_length = 15,default='')
    gender = models.CharField('性别',max_length=1,choices=GENDER,default='s')

    def __str__(self):
        return self.user.username

community/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import BlogUser

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model=BlogUser
        fields = ('mugshot','nickname','gender','telephone')

community/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import BlogUser
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate,login,logout
from json import dumps
from .forms import UserForm,UserProfileForm
from django.contrib.auth.decorators import login_required


def index(request):
    '''
    个人信息页面
    如果登陆了就显示个人信息等信息
    没有登陆则是一个空白界面
    '''
    if request.user.is_authenticated:
        user=request.user
        hasLogin=True
    else:
        hasLogin=False
        user=False
    if request.user.is_authenticated:  #django自带的一个判断是否为已登陆请求的方法
        user=request.user
        userProfile=BlogUser.objects.get(user=user)
        hasLogin=True
    else:
        userProfile=[]
    data={'userProfile':userProfile,'hasLogin':hasLogin,'user':user}
    return render(request, 'accounts/index.html',data)
@csrf_exempt
def register(request):
    '''
    注册账号
    '''
    if request.method == 'GET':
        if request.user.is_authenticated:
            user=request.user
            hasLogin=True
        else:
            hasLogin=False
            user=False
        userForm = UserForm()
        profileForm = UserProfileForm()
        data={'userForm':userForm,'profileForm':profileForm,'hasLogin':hasLogin,'user':user}
        return render(request, 'accounts/register.html', data)
    elif request.method == 'POST':
        userForm = UserForm(request.POST)
        userProfileForm = UserProfileForm(request.POST)
        if userForm.is_valid() and userProfileForm.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            profile=userProfileForm.save(commit=False)
            profile.user = user
            if 'mugshot' in request.FILES:
                profile.mugshot = request.FILES['mugshot']
            profile.save()
            # user_login(request)
            return HttpResponseRedirect('/user/')
        else:
            req={'message':'fail','reason':'未接收到正确的表单,或创建过程中出错'}
            return HttpResponse(dumps(req),content_type="application/json")

@csrf_exempt
def user_login(request):
    '''
    用户登陆页面
    登陆的后台逻辑
    '''
    if request.method == 'GET':
        if request.user.is_authenticated:
            user=request.user
            hasLogin=True
        else:
            hasLogin=False
            user=False
        data={'hasLogin':hasLogin,'user':user}
        return render(request, 'accounts/login.html', data)
    elif request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                req={'message':'success','reason':'登陆成功'}
                return HttpResponse(dumps(req),content_type="application/json")
            else:
                req={'message':'fail','reason':'该用户以被禁止登陆'}
            return HttpResponse(dumps(req),content_type="application/json")
        else:
            req={'message':'fail','reason':'错误的用户名和密码'}
            return HttpResponse(dumps(req),content_type="application/json")

@login_required
def user_logout(request):
    '''
    用户登出
    '''
    logout(request)
    return HttpResponseRedirect('/user/login')

@csrf_exempt
@login_required
def resetpassword(request):
    '''
    重置密码
    '''
    if request.method == 'GET':
        if request.user.is_authenticated:
            user=request.user
            hasLogin=True
        else:
            hasLogin=False
            user=False
        data={'hasLogin':hasLogin,'user':user}
        return render(request, 'accounts/resetpassword.html', data)
    elif request.method == 'POST':
        user=request.user
        user.set_password(request.POST['password'])
        user.save()
        req={'message':'success','reason':'更改成功'}
        return HttpResponse(dumps(req),content_type="application/json")
    else:
        req={'message':'fall','reason':'请求方式错误'}
        return HttpResponse(dumps(req),content_type="application/json")
        


@csrf_exempt
def getUserInfo(request):
    '''
    获取用户信息
    '''
    return HttpResponse('todo')

community/accounts/templates/accounts/head.html
{% load bootstrap4 %}
<head>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
{% comment %} bootstrap 资源 {% endcomment %}
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">  
<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>



</head>
<body>
<nav class="navbar-inverse navbar-default" role="navigation">
	<div class="container-fluid">
	<div class="navbar-header">
		<a class="navbar-brand" href="/">首页</a>
	</div>
	<div>
		<ul class="nav navbar-nav">
			<li class="active"><a href="/posting">论坛</a></li>
			{% comment %} 
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Java
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a href="#">jmeter</a></li>
					<li><a href="#">EJB</a></li>
					<li><a href="#">Jasper Report</a></li>
					<li class="divider"></li>
					<li><a href="#">分离的链接</a></li>
					<li class="divider"></li>
					<li><a href="#">另一个分离的链接</a></li>
				</ul>
			</li> {% endcomment %}
		</ul>
	</div>
    <ul class="nav navbar-nav navbar-right">
    {%if hasLogin%} 
      <li><a href="/posting/createposting"><span class="glyphicon glyphicon-file"></span>新建帖子</a></li>
      <li><a href="/user/resetpassword"><span class="glyphicon glyphicon-pencil"></span>更改密码</a></li>
      <li><a href="/user/"><span class="glyphicon glyphicon-user"></span> {{user.username}}</a></li>
      <li><a href="/user/logout"><span class="glyphicon glyphicon-log-in"></span> 登出</a></li>    
    {%else%}
      <li><a href="/user/register"><span class="glyphicon glyphicon-user"></span> 注册</a></li>
      <li><a href="/user/login"><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>
    {%endif%}
    </ul>
	</div>
</nav>

community/accounts/templates/accounts/index.html
{% include "./head.html" %}  
{% comment %} 引入使用include {% endcomment %}

<title>用户主页</title>
{% if hasLogin %}
<table class="table">
  <thead>
    <tr>
      <th>用户名</th>
      <th>邮箱</th>
      <th>昵称</th>
      <th>硬币</th>
      <th>电话号码</th>
      <th>性别</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{userProfile.user.username}}</td>
      <td>{{userProfile.user.email}}</td>
      <td>{{userProfile.nickname}}</td>
      <td>{{userProfile.icon}}</td>
      <td>{{userProfile.telephone}}</td>
      <td>{% if userProfile.gender == 's'%}
        保密
        {%elif userProfile.gender == 'm'%}
        男
        {% else %}
        女
        {%endif%}
      </td>
    </tr>
  </tbody>
</table>
{% else %}
<div class="container">
<h1><a href="/user/login">登陆</a>后可查看个人信息!</h1>
</div>
{% endif %}

community/accounts/templates/accounts/login.html
{% include "./head.html" %}
<title>登陆</title>


<div class="container">
<h2>请登陆 <a href="/user/register">没有账号</a>?</h2>
<br>
<div class="input-group">
<span class="input-group-addon">用户名</span>
	<input type="text" class="form-control" placeholder="" id="username">
</div>
<br>
<div class="input-group">
<span class="input-group-addon">密&nbsp;&nbsp;&nbsp;&nbsp码</span>
	<input type="password" class="form-control" placeholder="" id="password">
</div>
<br>
<p><a class="btn btn-primary btn-lg" role="button" onclick=send()>
登陆</a>
</p>

<div id="reason" ></div>
</div>



<script>
    function send()
    {
        var username = document.getElementById("username").value;
        var password = document.getElementById("password").value;

        $.post('', {'username':username, 'password':password},
        function(data){
            if(data['message']=="success"){
                console.log('成功');
                var reasonDiv=document.getElementById("reason");
                var reason=document.createElement("b");
                reason.innerText='登陆成功,即将跳转';
                reasonDiv.appendChild(reason);
                document.location.href="/user";
            }else{
                console.log('失败');
                var reasonDiv=document.getElementById("reason");
                var reason=document.createElement("b");
                reason.innerText=data['reason'];
                reasonDiv.appendChild(reason);
                reasonDiv.appendChild(document.createElement("br"));
            }
        }
        );
    }
</script>

community/accounts/templates/accounts/register.html
{% include "./head.html" %}
<div class="container">
<h2>请注册 <a href="/user/login">已有账号</a>?</h2>
<br>
<form id="user_form" method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ userForm.as_p }}
    {{ profileForm.as_p }}
    <input type="submit" name="submit" value="Register" />
</form>




{% comment %} <form class="form-inline" role="form" method="post" action=""  enctype="multipart/form-data">
<br><br>
<div class="input-group">
<span class="input-group-addon">用户名</span>
	<input type="text" class="form-control" placeholder="" name="username" id="id_username">
</div>
<br><br>
<div class="input-group">
<span class="input-group-addon">邮&nbsp;&nbsp;&nbsp;&nbsp;箱</span>
	<input type="email" name="email" class="form-control" placeholder="" id="id_email">
</div>
<br><br>
<div class="input-group">
<span class="input-group-addon">密&nbsp;&nbsp;&nbsp;&nbsp;码</span>
	<input type="password" name="password" class="form-control" placeholder="" id="id_password">
</div>
<br><br>
  <div class="form-group">
    <label class="sr-only" for="inputfile">文件输入</label>
    <input type="file" id="inputfile">
  </div>
<br><br>
<div class="input-group">
<span class="input-group-addon">昵&nbsp;&nbsp;&nbsp;&nbsp;称</span>
	<input type="text" name="nickname" class="form-control" placeholder="" id="id_nickname">
</div>
<br><br>
<div class="input-group">
<span class="input-group-addon">性&nbsp;&nbsp;&nbsp;&nbsp;别</span>
    <select class="form-control">
      <option value="s">保密</option>
      <option value="w">女孩子</option>
      <option value="m">男孩子</option>
    </select>
</div>
<br><br>
<div class="input-group">
<span class="input-group-addon">电&nbsp;&nbsp;&nbsp;&nbsp;话</span>
	<input type="text" name="telephone" class="form-control" placeholder="" id="id_telephone">
</div>
<br><br>
  <button type="submit" class="btn btn-default">提交</button>
</form> {% endcomment %}

community/accounts/templates/accounts/resetpassword.html
{% include "./head.html" %}
<title>重置密码</title>


<div class="container">
    <br>
        <div class="input-group" name="createComment">
            {% csrf_token %}
            <input type="password" class="form-control" placeholder="" id="password">
            <span class="input-group-addon" onclick=send()>重置密码</span>
        </div>
{% comment %} 
<label>新密码</label>
<input type="password" id="password"><br>

<input type="button" value="重置密码" onclick=send()> {% endcomment %}

</div>


<script>
    function send()
    {
        var password = document.getElementById("password").value;

        $.post('', {'password':password},
        function(data){
            if(data['message']=="success"){
                console.log('成功');
                document.location.href="/user/login";
            }
        }
        
        );
    }
</script>