community/community/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('posting.urls')),
    path('admin/', admin.site.urls),
]

community/posting/urls.py
from django.urls import path
from . import views

app_name='posting'
urlpatterns=[
    path('posting/',views.index,name='index'),
    path('posting/createposting/',views.createPosting), #发帖
    path('posting/createcomment/<int:postId>',views.createComment), #发评论
    path('posting/<str:postTitle>/',views.getPostByTitle), #查看帖子

]

community/posting/models.py
from django.db import models
from django.utils.timezone import now #当前时间
from accounts.models import BlogUser #导入django内建user模型

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(BlogUser,on_delete=models.CASCADE)
    title = models.CharField('标题', max_length=200, unique=True)
    body = models.TextField('正文')
    createDate = models.DateTimeField('创建时间', default=now)
    updateDate = models.DateTimeField('修改时间', default=now)
    
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-createDate']

    def GetPost(title=''):
        try:
            s=Post.objects.get(title=title)
            s.createDate=str(s.createDate)
            return s
        except:
            return '查询错误'


class Comment(models.Model):
    username = models.ForeignKey(BlogUser,on_delete=models.CASCADE)
    body = models.TextField('评论内容')
    createDate = models.DateTimeField('创建时间', default=now)
    updateDate = models.DateTimeField('修改时间', default=now)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)


    def __str__(self):
        return self.body
    class Meta:
        ordering = ['createDate']

community/posting/forms.py
from django import forms
from posting.models import Comment,Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body',)

community/posting/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Post,Comment
from accounts.models import BlogUser
from django.views.decorators.csrf import csrf_exempt
from json import dumps
from .forms import CommentForm,PostForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    '''
    主页
    '''
    postList=[]
    for i in Post.objects.all():
        postList.append(i.title)
    data={'postList':postList}

    #验证是否登陆
    if request.user.is_authenticated:
        user=request.user
        hasLogin=True
    else:
        hasLogin=False
        user=False
    data['hasLogin']=hasLogin
    return render(request, 'posting/index.html', data)

def getPostByTitle(request,postTitle):
    '''
    查看帖子
    '''
    if request.method == 'GET':
        post=Post.GetPost(title=postTitle)
        if post=='查询错误':
            html='查询错误'
            return HttpResponse(html)

        comment = post.comment_set.all() #评论集
        comment = comment.order_by('-createDate') #按照发送时间排序
        commentForm = CommentForm()

        data={
            'post':post,
            'comment':comment,
            'commentForm':commentForm,
        }
        #验证是否登陆
        if request.user.is_authenticated:
            user=request.user
            hasLogin=True
        else:
            hasLogin=False
            user=False
        data['hasLogin']=hasLogin
        return render(request, 'posting/post.html', data)
    elif request.method == 'POST':
        createComment(request)
    else:
        req={'message':'fail','reason':'请求方式错误'}
        return HttpResponse(dumps(req),content_type="application/json")


@csrf_exempt
@login_required
def createComment(request,postId):
    '''
    添加评论
    只有登陆后才能登陆
    '''
    if request.method == 'POST':
        commentForm=CommentForm(request.POST)
        if commentForm.is_valid():
            try:
                post1=Post.objects.get(pk=postId)
                username=BlogUser.objects.get(user=request.user)
                Comment(username=username,body=request.POST['body'],post=post1).save()
            except:
                req={'message':'fall','reason':'该帖子不存在或被删除,无法回复'}
                return HttpResponse(dumps(req),content_type="application/json")

            req={'message':'success','reason':'评论成功'}
            return HttpResponse(dumps(req),content_type="application/json")
        else:
            req={'message':'fail','reason':'未接收到正确的表单,或创建过程中出错'}
            return HttpResponse(dumps(req),content_type="application/json")

    else:
        req={'message':'fail','reason':'请求方式失败'}
        return HttpResponse(dumps(req),content_type="application/json")

@login_required
@csrf_exempt
def createPosting(request):
    '''
    创建帖子
    '''
    if request.method == 'POST':  #post请求创建post
        postForm=PostForm(request.POST)
        if postForm.is_valid():
            postForm=postForm.save(commit=False)
            user=BlogUser.objects.get(user=request.user)
            postForm.author=user
            postForm.save()
            req={'message':'success','reason':'发帖成功'}
            return HttpResponse(dumps(req),content_type="application/json")
        else:
            req={'message':'fail','reason':'发帖失败'}
            return HttpResponse(dumps(req),content_type="application/json")


    elif request.method == 'GET':  #get请求返回页面
        postForm = PostForm()
        data={
            'postForm':postForm,
        }
        #验证是否登陆
        if request.user.is_authenticated:
            user=request.user
            hasLogin=True
        else:
            hasLogin=False
            user=False
        data['hasLogin']=hasLogin
        return render(request, 'posting/createPost.html', data)
    else:
        req={'message':'fail','reason':'请求方式错误'}
        return HttpResponse(dumps(req),content_type="application/json")

community/posting/templates/posting/createPost.html
{% include "./head.html" %}
<title>发布新帖</title>


<div class="container">
    {% csrf_token %}
    
    <div class="input-group input-group-lg">
        <span class="input-group-addon">标题</span>
        <input type="text" class="form-control" placeholder="" name="title" id="id_title">
    </div>
    <br>
        <textarea name="body" class="form-control" rows="8" id="id_body"></textarea>
    <br>

    <button class="btn btn-primary" onclick=send()>发布</button>

<div id="reason" ></div>

</div>


<script>
    function send()
    {
        var title = document.getElementById("id_title").value;
        var body = document.getElementById("id_body").value;
        var csrfmiddlewaretoken = document.getElementsByName('csrfmiddlewaretoken')[0].value;

        $.post('', {'title':title, 'body':body,'csrfmiddlewaretoken':csrfmiddlewaretoken},
        function(data){
            if(data['message']=="success"){
                console.log('成功');
                var reasonDiv=document.getElementById("reason");
                var reason=document.createElement("b");
                reason.innerText='登陆成功,即将跳转';
                reasonDiv.appendChild(reason);
                document.location.href="/posting";
            }else{
                console.log('失败');
                var reasonDiv=document.getElementById("reason");
                var reason=document.createElement("b");
                reason.innerText=data['reason'];
                reasonDiv.appendChild(reason);
                reasonDiv.appendChild(document.createElement("br"));
            }
        }
        );
    }
</script>

{% comment %} 原始发送页面代码
<form id="user_form" method="post" action="/posting/createposting/" enctype="multipart/form-data">
    {% csrf_token %}
     {{ postForm.as_p }}
    <input type="submit" name="createComment" value="发送" />
     {% endcomment %}

community/posting/templates/posting/head.html
{% load bootstrap4 %}
<head>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
{% comment %} bootstrap 资源 {% endcomment %}
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">  
<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>



</head>
<body>
<nav class="navbar-inverse navbar-default" role="navigation">
	<div class="container-fluid">
	<div class="navbar-header">
		<a class="navbar-brand" href="/">首页</a>
	</div>
	<div>
		<ul class="nav navbar-nav">
			<li class="active"><a href="/posting">论坛</a></li>
			{% comment %} 
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Java
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a href="#">jmeter</a></li>
					<li><a href="#">EJB</a></li>
					<li><a href="#">Jasper Report</a></li>
					<li class="divider"></li>
					<li><a href="#">分离的链接</a></li>
					<li class="divider"></li>
					<li><a href="#">另一个分离的链接</a></li>
				</ul>
			</li> {% endcomment %}
		</ul>
	</div>
    <ul class="nav navbar-nav navbar-right">
    {%if hasLogin%} 
      <li><a href="/posting/createposting"><span class="glyphicon glyphicon-file"></span>新建帖子</a></li>
      <li><a href="/user/resetpassword"><span class="glyphicon glyphicon-pencil"></span>更改密码</a></li>
      <li><a href="/user/"><span class="glyphicon glyphicon-user"></span> {{user.username}}</a></li>
      <li><a href="/user/logout"><span class="glyphicon glyphicon-log-in"></span> 登出</a></li>    
    {%else%}
      <li><a href="/user/register"><span class="glyphicon glyphicon-user"></span> 注册</a></li>
      <li><a href="/user/login"><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>
    {%endif%}
    </ul>
	</div>
</nav>

community/posting/templates/posting/index.html
{% include "./head.html" %}
<title>帖子专区</title>

<div class="container">
{%for i in postList%}

<h2><a href="{{i}}">{{i}}</a></h2>

{% endfor %}
</div>

community/posting/templates/posting/post.html
{% include "./head.html" %}
<title>{{post.title}}</title>


<div class="container">
    <div name="artical">
    <h1>{{post.title}}</h1>
    <h6><b>作者  </b>{{post.author}}</h6>
    <h4>{{post.body}}</h4>
    </div>

    <div name="commentList">
        <div name="comment" id="commentList"></div>
        {%for i in comment%}
        <div name="comment" id="commentList">
            <b>{{i.username}}</b>
            <p>{{i.body}}<br>
            <b>{{i.createDate}}</b></p>
        </div>
        {% endfor %}
        <hr>
        <div class="input-group" name="createComment">
            {% csrf_token %}
            <input type="text" class="form-control" placeholder="" id="id_body">
            <span class="input-group-addon" onclick=send()>发表评论</span>
        </div>
        <div id="reason" name="reason"></div>
    </div>


</div>


{% comment %} {{post.title}}<br>
{{post.author}}<br>
{{post.body}}<br>
{{post.createDate}}<br>
{{post.updateDate}}<br>

{%for i in comment%}

<hr>
<b>{{i.username}}</b><br>
{{i.body}}</br>
{{i.createDate}}

{% endfor %}
<form id="user_form" method="post" action="/posting/createcomment/{{post.id}}" enctype="multipart/form-data">
    {% csrf_token %}
     {{ commentForm.as_p }}
    <input type="submit" name="createComment" value="发送" />
</form>

{% endcomment %}


<script>
    function send()
    {
        var body = document.getElementById("id_body").value;
        var csrfmiddlewaretoken = document.getElementsByName('csrfmiddlewaretoken')[0].value;

        $.post('/posting/createcomment/{{post.id}}', {'body':body,'csrfmiddlewaretoken':csrfmiddlewaretoken},
        function(data){
            if(data['message']=="success"){
                console.log('成功');
                var $com=$("<div name='comment'><b>{{user.username}}</b><p>"+body+"<br><b>刚刚</b></p>");
                $("#commentList").prepend($com);
            }else{
                console.log('失败');
                var reasonDiv=document.getElementById("reason");
                var reason=document.createElement("b");
                reason.innerText=data['reason'];
                reasonDiv.appendChild(reason);
                reasonDiv.appendChild(document.createElement("br"));
            }
        }
        );
    }
</script>